print ("Este es un programa que calcula el área de figuras")
print ("indica cuanto mide el lado del cuadrado")
ladoCuadrado=input()
areaCuadrado=float(ladoCuadrado)*float(ladoCuadrado)
print ("el area del cuadrado es:")
print (areaCuadrado)
print ("ahora vamos a calcular el area del rectangulo")
print ("indica cuanto mide lado base del rectangulo")
ladoBase=input()
print ("indica cuanto mide la altura")
ladoAltura=input()
areaRectangulo=float(ladoBase)*float(ladoAltura)
print ("el area del rectangulo es:")
print (areaRectangulo)